description: This configuration is required only when the subscription type is INLINE.
type: object
title: Inline Config
properties:
  error:
    type: string
    description: An error message.
    example: "Access is denied"
  output:
    type: object
    description: The details of the inline configuration.
    example: {"accessRequestId": "1234"}
