post:
  operationId: createSearchAttributeConfig
  tags:
    - Search Attribute Configuration
  summary: Create Extended Search Attributes
  description: >-
    Create and configure extended search attributes. This API accepts an attribute name, an attribute display name and a list of name/value pair associates of application IDs
    to attribute names. It will then validate the inputs and configure/create and attribute promotion configuration in the Link ObjectConfig.

    A token with ORG_ADMIN authority is required to call this API.
  requestBody:
    required: true
    content:
      application/json:
        schema:
          $ref: '../schemas/SearchAttributeConfig.yaml'
        example: {
          "name": "newMailAttribute",
          "displayName": "New Mail Attribute",
          "applicationAttributes": {
            "2c9180866166b5b0016167c32ef31a66": "mail",
            "2c9180866166b5b0016167c32ef31a67": "mail"
          }
        }
  responses:
    '202':
      $ref: '../../v3/responses/202.yaml'
    '400':
      $ref: '../../v3/responses/400.yaml'
    '401':
      $ref: '../../v3/responses/401.yaml'
    '403':
      $ref: '../../v3/responses/403.yaml'
    '404':
      $ref: '../../v3/responses/404.yaml'
    '429':
      $ref: '../../v3/responses/429.yaml'
    '500':
      $ref: '../../v3/responses/500.yaml'

get:
  operationId: getSearchAttributeConfig
  tags:
    - Search Attribute Configuration
  summary: List Extended Search Attributes
  description: >-
    Get a list of attribute/application associates currently configured in Identity Security Cloud (ISC).

    A token with ORG_ADMIN authority is required to call this API.
  responses:
    '200':
      description: List of attribute configurations in ISC.
      content:
        application/json:
          schema:
            type: array
            items:
              $ref: '../schemas/SearchAttributeConfig.yaml'
    '401':
      $ref: '../../v3/responses/401.yaml'
    '403':
      $ref: '../../v3/responses/403.yaml'
    '429':
      $ref: '../../v3/responses/429.yaml'
    '500':
      $ref: '../../v3/responses/500.yaml'