get:
  tags:
    - Connectors
  operationId: getConnectorCorrelationConfig
  summary: Get connector correlation configuration
  description: >-
    Fetches a connector's correlation config using its script name.    
  parameters:
    - name: scriptName
      in: path
      description: The scriptName value of the connector. Scriptname is the unique id generated at connector creation.
      required: true
      x-sailpoint-resource-operation-id: getConnectorList
      style: simple
      explode: false
      schema:
        type: string
        example: aScriptName
  responses:
    '200':
      description: The connector's correlation config
      content:
        application/xml:
          schema:
            type: string
    '400':
      $ref: '../responses/400.yaml'
    '401':
      $ref: '../responses/401.yaml'
    '403':
      $ref: '../responses/403.yaml'
    '404':
      $ref: '../responses/404.yaml'
    '429':
      $ref: '../responses/429.yaml'
    '500':
      $ref: '../responses/500.yaml'
  security:
    - userAuth: [ idn:connector-config:read, idn:connector-config:manage ]
  x-sailpoint-userLevels:
    - ORG_ADMIN
    - SOURCE_ADMIN
    - SOURCE_SUBADMIN
put:
  tags:
    - Connectors
  operationId: putConnectorCorrelationConfig
  summary: Update connector correlation configuration
  description: >-
    Update a connector's correlation config using its script name.    
  parameters:
    - name: scriptName
      in: path
      description: The scriptName value of the connector. Scriptname is the unique id generated at connector creation.
      required: true
      x-sailpoint-resource-operation-id: getConnectorList
      style: simple
      explode: false
      schema:
        type: string
        example: aScriptName
  requestBody:
    required: true
    content:
      multipart/form-data:
        schema:
          type: object
          required:
            - file
          properties:
            file:
              type: string
              description: connector correlation config xml file
              format: binary
  responses:
    '200':
      description: The connector's update detail
      content:
        application/json:
          schema:
            $ref: '../schemas/UpdateDetail.yaml'
    '400':
      $ref: '../responses/400.yaml'
    '401':
      $ref: '../responses/401.yaml'
    '403':
      $ref: '../responses/403.yaml'
    '404':
      $ref: '../responses/404.yaml'
    '429':
      $ref: '../responses/429.yaml'
    '500':
      $ref: '../responses/500.yaml'
  security:
    - userAuth: [ idn:connector-config:manage ]
  x-sailpoint-userLevels:
    - ORG_ADMIN
    - SOURCE_ADMIN
    - SOURCE_SUBADMIN