delete:
  operationId: deleteMFAConfig
  tags:
    - MFA Configuration
  summary: Delete MFA method configuration
  description: >-
    This API removes the configuration for the specified MFA method.
  security:
    - userAuth: [idn:mfa-configuration:manage]
  x-sailpoint-userLevels:
    - ORG_ADMIN
  parameters:
    - in: path
      name: method
      schema:
        type: string
        example: okta-verify
        nullable: false
        enum:
          - okta-verify
          - duo-web
      required: true
      description: >-
        The name of the MFA method.
        The currently supported method names are 'okta-verify' and 'duo-web'.
  responses:
    "200":
      description: MFA configuration of an MFA method.
      content:
        application/json:
          schema:
            $ref: "../schemas/MfaOktaConfig.yaml"
          example:
            {
              "mfaMethod": "okta-verify",
              "enabled": true,
              "host": "www.example.com",
              "accessKey": "d******Y",
              "identityAttribute": "email",
            }
    "400":
      $ref: "../responses/400.yaml"
    "401":
      $ref: "../responses/401.yaml"
    "403":
      $ref: "../responses/403.yaml"
    "429":
      $ref: "../responses/429.yaml"
    "500":
      $ref: "../responses/500.yaml"
