get:
  operationId: getTenantConfigConfiguration
  tags:
  - Work Reassignment
  summary: Get tenant-wide reassignment configuration settings
  description: Gets the global Reassignment Configuration settings for the requestor's
    tenant.
  security:
  - userAuth:
    - idn:reassignment-tenant-configuration:read
  responses:
    '200':
      description: Tenant-wide Reassignment Configuration settings
      content:
        application/json:
          schema:
            $ref: ../schemas/work-reassignment/TenantConfigurationResponse.yaml
    '400':
      $ref: ../responses/400.yaml
    '401':
      $ref: ../responses/401.yaml
    '403':
      $ref: ../responses/403.yaml
    '404':
      $ref: ../responses/404.yaml
    '429':
      $ref: ../responses/429.yaml
    '500':
      $ref: ../responses/500.yaml
  parameters:
  - name: X-SailPoint-Experimental
    in: header
    description: Use this header to enable this experimental API.
    example: true
    schema:
      type: string
      default: true
    required: true
put:
  operationId: putTenantConfiguration
  tags:
  - Work Reassignment
  summary: Update tenant-wide reassignment configuration settings
  description: Replaces existing Tenant-wide Reassignment Configuration settings with
    the newly provided settings.
  security:
  - userAuth:
    - idn:reassignment-tenant-configuration:update
  requestBody:
    required: true
    content:
      application/json:
        schema:
          $ref: ../schemas/work-reassignment/TenantConfigurationRequest.yaml
  responses:
    '200':
      description: Tenant-wide Reassignment Configuration settings
      content:
        application/json:
          schema:
            $ref: ../schemas/work-reassignment/TenantConfigurationResponse.yaml
    '400':
      $ref: ../responses/400.yaml
    '401':
      $ref: ../responses/401.yaml
    '403':
      $ref: ../responses/403.yaml
    '429':
      $ref: ../responses/429.yaml
    '500':
      $ref: ../responses/500.yaml
  parameters:
  - name: X-SailPoint-Experimental
    in: header
    description: Use this header to enable this experimental API.
    example: true
    schema:
      type: string
      default: true
    required: true
