description: Client Runtime Logging Configuration
nullable: true
type: object
required:
  - durationMinutes
  - rootLevel
properties:
  clientId:
    description: Log configuration's client ID
    type: string
    example: aClientId
  durationMinutes:
    description: Duration in minutes for log configuration to remain in effect before resetting to defaults
    type: integer
    format: int32
    example: 120
    minimum: 5
    maximum: 1440
  expiration:
    description: Expiration date-time of the log configuration request
    example: "2020-12-15T19:13:36.079Z"
    type: string
    format: date-time
  rootLevel:
    description: Root log level to apply, the default level for all logs. For more information about logging levels, refer to the "Logging Levels" table in [Enabling Connector Logging in IdentityNow](https://community.sailpoint.com/t5/IdentityNow-Articles/Enabling-Connector-Logging-in-IdentityNow/ta-p/188107).
    default: INFO
    example: INFO
    $ref: './StandardLevel.yaml'
  logLevels:
    description: Map of log level by key. The keys are logging classes, and the values are logging levels. To see the available connectors and their logging classes, refer to the "Logging Classes" table in [Enabling Connector Logging in IdentityNow](https://community.sailpoint.com/t5/IdentityNow-Articles/Enabling-Connector-Logging-in-IdentityNow/ta-p/188107).
    example: {
        "sailpoint.connector.ADLDAPConnector": "INFO"
    }
    $ref: './LogLevelSpec.yaml'
