type: object
properties:
  assignmentRule:
    type: string
    enum:
      - MANAGER
      - STATIC
    description: >-
      Details about the violations owner.

      MANAGER - identity's manager

      STATIC - Governance Group or Identity
    example: MANAGER
  ownerRef:
    $ref: './BaseReferenceDto.yaml'

