get:
  operationId: getAuthOrgLockoutConfig
  tags:
    - Global Tenant Security Settings
  summary: Get auth org lockout configuration.
  description: This API returns the details of an org's lockout auth configuration.
  security:
    - userAuth:
        - sp:auth-org:read
    - applicationAuth:
        - sp:auth-org:read
  responses:
    '200':
      description: Lockout configuration for the tenant's auth org.
      content:
        application/json:
          schema:
            $ref: ../schemas/LockoutConfiguration.yaml
    '400':
      $ref: ../responses/400.yaml
    '401':
      $ref: ../responses/401.yaml
    '403':
      $ref: ../responses/403.yaml
    '404':
      $ref: ../responses/404.yaml
    '429':
      $ref: ../responses/429.yaml
    '500':
      $ref: ../responses/500.yaml
patch:
  operationId: patchAuthOrgLockoutConfig
  tags:
    - Global Tenant Security Settings
  summary: Update auth org lockout configuration
  description: |
    This API updates an existing lockout configuration for an org using PATCH
  security:
    - userAuth:
        - sp:auth-org:manage
    - applicationAuth:
        - sp:auth-org:manage
  x-sailpoint-userLevels:
    - ORG_ADMIN
    - HELPDESK
  requestBody:
    required: true
    description: |-
      A list of auth org lockout configuration update operations according to the [JSON Patch](https://tools.ietf.org/html/rfc6902) standard.
      Ensures that the patched Lockout Config conforms to certain logical guidelines, which are:
        `1. maximumAttempts >= 1 && maximumAttempts <= 15
        2. lockoutDuration >= 5 && lockoutDuration <= 60
        3. lockoutWindow >= 5 && lockoutDuration <= 60`
    content:
      application/json-patch+json:
        schema:
          type: array
          items:
            $ref: ../schemas/JsonPatchOperation.yaml
        example:
          - op: replace
            path: /maximumAttempts
            value: 7,
          - op: add
            path: /lockoutDuration
            value: 35
  responses:
    '200':
      description: Updated Auth Org lockout configuration.
      content:
        application/json:
          schema:
            $ref: ../schemas/LockoutConfiguration.yaml
    '400':
      $ref: ../responses/400.yaml
    '401':
      $ref: ../responses/401.yaml
    '403':
      $ref: ../responses/403.yaml
    '404':
      $ref: ../responses/404.yaml
    '429':
      $ref: ../responses/429.yaml
    '500':
      $ref: ../responses/500.yaml
