post:
  operationId: startApplicationDiscovery
  tags:
    - Application Discovery
  summary: Start Application Discovery
  security:
    - userAuth:
        - 'idn:application-discovery:write'
  x-sailpoint-userLevels:
    - ORG_ADMIN
    - SOURCE_ADMIN
  description: Use this API to discover applications.
  requestBody:
    required: true
    content:
      application/json:
        schema:
          $ref: '../schemas/ApplicationDiscoveryRequest.yaml'
  responses:
    '200':
      description: Application Discovery task was started successfully.
      content:
        application/json:
          schema:
            $ref: '../schemas/ApplicationDiscoveryResponse.yaml'
    '400':
      $ref: '../responses/400.yaml'
    '401':
      $ref: '../responses/401.yaml'
    '403':
      $ref: '../responses/403.yaml'
    '404':
      $ref: '../responses/404.yaml'
    '429':
      $ref: '../responses/429.yaml'
    '500':
      $ref: '../responses/500.yaml'
  parameters:
    - name: X-SailPoint-Experimental
      in: header
      description: Use this header to enable this experimental API.
      example: true
      schema:
        type: string
        default: true
      required: true
