get:
  operationId: listSpConfigObjects
  security:
    - userAuth: [sp:config:read, sp:config:manage]
  x-sailpoint-userLevels:
    - ORG_ADMIN
  tags:
  - SP-Config
  summary: List config objects
  description: Get a list of object configurations that the tenant export/import service knows.
  responses:
    '200':
      description: Object configurations returned successfully.
      content:
        application/json:
          schema:
            type: array
            items:
              $ref: ../schemas/SpConfigObject.yaml
    '400':
      $ref: ../responses/400.yaml
    '401':
      $ref: ../responses/401.yaml
    '403':
      $ref: ../responses/403.yaml
    '404':
      $ref: ../responses/404.yaml
    '429':
      $ref: ../responses/429.yaml
    '500':
      $ref: ../responses/500.yaml
