allOf:
  - $ref: './BaseCreateApplicationRequest.yaml'
  - required:
      - domain
      - password
      - server
      - user
    type: object
    properties:
      domain:
        type: string
        description: The domain for Windows File Server authentication.
        example: "CORP"
      server:
        type: string
        description: The Windows File Server address.
        example: "fileserver.company.com"
      user:
        type: string
        description: The username for Windows File Server authentication.
        example: "wfuser"
      password:
        type: string
        description: The password for Windows File Server authentication.
        example: "wfpassword"
      isCluster:
        type: boolean
        description: Indicates whether the server is part of a cluster.
        example: false
        default: false
      clusterNodes:
        type: array
        items:
          type: string
        nullable: true
        description: List of cluster node addresses.
        example: ["node1.company.com", "node2.company.com"]
