get:
  operationId: getDiscoveredApplications
  tags:
    - Application Discovery
  summary: Retrieve discovered applications for tenant
  description: >
    Get a list of applications that have been identified within the environment. This includes details such as application names, discovery dates, potential correlated saas_vendors and related suggested connectors.
  security:
    - userAuth:
        - 'idn:application-discovery:read'
  parameters:
    - $ref: '../../v3/parameters/limit.yaml'
    - $ref: '../../v3/parameters/offset.yaml'
    - in: query
      name: detail
      schema:
        type: string
        enum: [ SLIM, FULL ]
      description: >-
        Determines whether slim, or increased level of detail is provided for each discovered application in the returned list.
        SLIM is the default behavior.
      example: FULL
    - in: query
      name: filter
      schema:
        type: string
      description: >
        Filter results using the standard syntax described in [V3 API Standard Collection Parameters](https://developer.sailpoint.com/idn/api/standard-collection-parameters#filtering-results)
          
          
        Filtering is supported for the following fields and operators:
        
        
        **name**: *eq, sw, co*
        
        
        **description**: *eq, sw, co*
        
        
        **createdAtStart**: *eq, le, ge*


        **createdAtEnd**: *eq, le, ge*
        
        
        **discoveredAtStart**: *eq, le, ge*
        
        
        **discoveredAtEnd**: *eq, le, ge*


        **discoverySource**: *eq, in*
      example: name eq "Okta" and description co "Okta" and discoverySource in ("csv", "Okta Saas")
      required: false
      style: form
    - in: query
      name: sorters
      schema:
        type: string
        format: comma-separated
      description: >-
        Sort results using the standard syntax described in [V3 API Standard Collection Parameters](https://developer.sailpoint.com/idn/api/standard-collection-parameters#sorting-results)


        Sorting is supported for the following fields: **name, description, discoveredAt, discoverySource**
      example: name
  responses:
    '200':
      description: List of discovered applications. By default, the API returns a list of SLIM discovered applications.
      content:
        application/json:
          schema:
            type: array
            items:
              oneOf:
                - $ref: '../schemas/SlimDiscoveredApplications.yaml'
                - $ref: '../schemas/FullDiscoveredApplications.yaml'
          examples:
            Slim Discovered Application:
              $ref: '../schemas/discovered-applications/examples/SlimDiscoveredApplications.yaml'
            Discovered Application:
              $ref: '../schemas/discovered-applications/examples/FullDiscoveredApplications.yaml'
    '400':
      $ref: '../../v3/responses/400.yaml'
    '401':
      $ref: '../../v3/responses/401.yaml'
    '403':
      $ref: '../../v3/responses/403.yaml'
    '429':
      $ref: '../../v3/responses/429.yaml'
    '500':
      $ref: '../../v3/responses/500.yaml'