type: object
properties:
  customInstructionsEnabled:
    type: boolean
    description: Indicator whether custom password instructions feature is enabled. The default value is false.
    default: false
    example: true
  digitTokenEnabled:
    type: boolean
    description: Indicator whether "digit token" feature is enabled. The default value is false.
    default: false
    example: true
  digitTokenDurationMinutes:
    type: integer
    format: int32
    description: The duration of "digit token" in minutes. The default value is 5.
    minimum: 1
    maximum: 60
    default: 5
    example: 10
  digitTokenLength:
    type: integer
    format: int32
    description: The length of "digit token". The default value is 6.
    minimum: 6
    maximum: 18
    default: 6
    example: 9