type: object
title: Config Object Rule
description: Format of Config Hub object rules.
properties:
  path:
    type: string
    description: JSONPath expression denoting the path within the object where a value substitution should be applied.
    example: $.enabled
  value:
    anyOf:
      - type: object
      - type: array
      - type: string
      - type: number
      - type: boolean
    nullable: true
    description: Value to be assigned at the jsonPath location within the object.
  modes:
    type: array
    description: Draft modes the rule will apply to.
    items:
      type: string
      enum:
        - RESTORE
        - PROMOTE
        - UPLOAD
    example: [RESTORE, PROMOTE]