get:
  operationId: getAccessRequestConfig
  security:
    - userAuth: [ idn:access-request-config:read ]
  summary: Get Access Request Configuration
  tags:
    - Access Requests
  description: >-
    This endpoint returns the current access-request configuration.
  responses:
    '200':
      description: Access Request Configuration Details.
      content:
        application/json:
          schema:
            $ref: '../schemas/AccessRequestConfig.yaml'
    '400':
      $ref: '../responses/400.yaml'
    '401':
      $ref: '../responses/401.yaml'
    '403':
      $ref: '../responses/403.yaml'
    '429':
      $ref: '../responses/429.yaml'
    '500':
      $ref: '../responses/500.yaml'

put:
  operationId: setAccessRequestConfig
  security:
    - userAuth: [ idn:access-request-config:update ]
  x-sailpoint-userLevels:
    - ORG_ADMIN
  summary: Update Access Request Configuration
  tags:
    - Access Requests
  description: >-
    This endpoint replaces the current access-request configuration.
  requestBody:
       required: true
       content:
         application/json:
           schema:
             $ref: '../schemas/AccessRequestConfig.yaml'
  responses:
    '200':
      description: Access Request Configuration Details.
      content:
        application/json:
          schema:
            $ref: '../schemas/AccessRequestConfig.yaml'
    '400':
      $ref: '../responses/400.yaml'
    '401':
      $ref: '../responses/401.yaml'
    '403':
      $ref: '../responses/403.yaml'
    '429':
      $ref: '../responses/429.yaml'
    '500':
      $ref: '../responses/500.yaml'