description: List of discovered applications
value:
  - id: "09d88a67-bae8-422c-a09b-f7a72f5ab032"
    name: "Example App"
    discoverySource: "csv"
    discoveredVendor: "Example Vendor"
    description: "An application for managing examples."
    recommendedConnectors: ["ConnectorA", "ConnectorB"]
    discoveredAt: "2023-07-01T12:00:00Z"
    createdAt: "2024-06-01T12:00:00Z"
    status: "ACTIVE"
    operationalStatus: "Operational"
    datasetId: null
    discoverySourceCategory: "csv"
    licenseCount: null
    isSanctioned: false
    logo: null
    appUrl: null
    groups: null
    usersCount: null
    applicationOwner:
      - "Ms. jane.doe"
    itApplicationOwner:
      - "Mr. mark.smith"
    businessCriticality: "Medium"
    dataClassification: "Confidential"
    businessUnit: "Operations"
    installType: null
    environment: null
    riskScore: null
    isPrivileged: false
    warrantyExpiration: null
    attributes: null

  - id: "59310a1e-0d8f-42fa-95aa-b82b263de7f6"
    name: "Sample Tracker"
    discoverySource: "ServiceNow CMDB"
    discoveredVendor: "Sample Vendor"
    description: "A tool for monitoring and managing samples."
    recommendedConnectors: ["ConnectorC", "ConnectorD"]
    discoveredAt: "2023-08-15T08:00:00Z"
    createdAt: "2024-05-20T08:00:00Z"
    status: "ACTIVE"
    operationalStatus: "Operational"
    datasetId: "cmdb-servicenow:applications"
    discoverySourceCategory: "cmdb"
    licenseCount: ""
    isSanctioned: false
    logo: ""
    appUrl: ""
    groups: null
    usersCount: ""
    applicationOwner:
      - "Ms. lisa.brown"
    itApplicationOwner:
      - "Mr. david.lee"
    businessCriticality: "High"
    dataClassification: "Internal"
    businessUnit: "R&D"
    installType: "SaaS"
    environment: "Production"
    riskScore: "MEDIUM"
    isPrivileged: false
    warrantyExpiration: "2024-09-01T00:00:00.000+0000"
    attributes:
      identityStack: "NOT_SHARED"
      selfService: false
      signOnMode: "SAML_2_0"

  - id: "dfe675cb-f689-475f-99f1-49e348449867"
    name: "Demo Manager"
    discoverySource: "Okta SaaS"
    discoveredVendor: "Demo Provider"
    description: "Software to demonstrate basic functionalities."
    recommendedConnectors: ["ConnectorE", "ConnectorF"]
    discoveredAt: "2023-09-10T15:00:00Z"
    createdAt: "2024-07-03T15:00:00Z"
    status: "ACTIVE"
    operationalStatus: "Operational"
    datasetId: "sso-okta:applications"
    discoverySourceCategory: "sso"
    licenseCount: 175
    isSanctioned: true
    logo: "https://spdojtest1.oktapreview.com/api/v1/apps/0oaeuef9hiipHcMgR0h7/logo"
    appUrl: "https://spdojtest1.oktapreview.com/home/salesforce/0oaeuef9hiipHcMgR0h7/24"
    groups:
      - map:
          id: "id"
          name: "JIRA Users"
          nativeIdentifiers:
            map:
              distinguishedName: "CN=Engineering users,OU=Engineering,DC=corp,DC=example,DC=com"
              id: "nativeId"
              objectSid: "S-1-5-21-717838489-685202119-709183397-1177"
          type: "EXTERNAL_GROUP|LOCAL_GROUP"
    usersCount: "175"
    applicationOwner:
      - "Mr. abel.tuter"
    itApplicationOwner:
      - "Mr. john doe"
    businessCriticality: "High"
    dataClassification: "Restricted"
    businessUnit: "Finance"
    installType: "On Premise"
    environment: "Production"
    riskScore: "ANY"
    isPrivileged: false
    warrantyExpiration: "2023-09-25T14:07:27.000+0000"
    attributes:
      features:
        - "IMPORT_PROFILE_UPDATES"
        - "IMPORT_USER_SCHEMA"
        - "IMPORT_NEW_USERS"
      identityStack: "NOT_SHARED"
      selfService: false
      signOnMode: "SAML_2_0"
