type: string
description: Enum list of valid work types that can be selected for a Reassignment Configuration
enum:
  - ACCESS_REQUESTS
  - CERTIFICATIONS
  - MANUAL_TASKS
  - GENERIC_APPROVALS
example: ACCESS_REQUESTS